### ISSUE TITLE
博主您好，这个问题怎么解决

### ISSUE THREAD

**Issue by daydreamertu** [huangzongmou/yolov8_Distillation#15]
Traceback (most recent call last):
  File "E:\Projects\1\yolov8_Distillation-master\train.py", line 30, in <module>
    model_s.train(data="ultralytics/cfg/datasets/ship_SSDD.yaml", epochs=100, device=0 ,imgsz=640,name="runs/train/SSDD_distillation", workers=0, Distillation = model_t.model)
  File "E:\Projects\1\yolov8_Distillation-master\ultralytics\yolo\engine\model.py", line 376, in train
    self.trainer.train()
  File "E:\Projects\1\yolov8_Distillation-master\ultralytics\yolo\engine\trainer.py", line 406, in train
    self._do_train(world_size)
  File "E:\Projects\1\yolov8_Distillation-master\ultralytics\yolo\engine\trainer.py", line 559, in _do_train
    preds = self.model(batch['img'])
  File "E:\Anaconda\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Projects\1\yolov8_Distillation-master\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
  File "E:\Projects\1\yolov8_Distillation-master\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "E:\Projects\1\yolov8_Distillation-master\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
  File "E:\Anaconda\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Projects\1\yolov8_Distillation-master\ultralytics\nn\modules\block.py", line 232, in forward
    return self.cv2(torch.cat(y, 1))
RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 8.00 GiB total capacity; 12.24 GiB already allocated; 0 bytes free; 12.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by yhengYE** [comment]
换大点的gpu 你这爆显存了
